version: '3.0'

services:
  grafana:
    container_name: 'grafana-deep-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
    ports:
      - 3000:3000/tcp # This needs to be port 3000 for e2e tests
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-deep-panel
      - ./provisioning:/etc/grafana/provisioning
