version: '3.0'

services:
  grafana:
    container_name: 'grafana-deep-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3100:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-deep-panel
      - /home/bdonnell/repo/github/intergral/grafana-deep-datasource/dist:/var/lib/grafana/plugins/grafana-deep-datasource
      - ./provisioning:/etc/grafana/provisioning
