site_name: Deep Grafana Panel
site_url: https://intergral.github.com/grafana-deep-panel/

repo_name: Grafana Deep Panle
repo_url: https://github.com/intergral/grafana-deep-datasource

copyright: Intergral GmbH 2023

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
